### Appirence
[theme]
theme = "ctp-mocha"
[theme.overrides]
separator = " "
separator_bg = "#1e1e2e"

[icons]
icons = "awesome6"

### Blocks
[[block]]
block = "scratchpad"

# disk space
[[block]]
block = "disk_space"
path = "/"
info_type = "used"
interval = 30
warning = 70.0
alert = 80.0
format = " $percentage $icon "
format_alt = " $used/$total $icon "
if_command = "[ \"$(df -P /home | awk 'NR==2 {print $1}')\" = \"$(df -P / | awk 'NR==2 {print $1}')\" ]"
merge_with_next = false

[[block]]
block = "disk_space"
path = "/"
info_type = "used"
interval = 30
warning = 70.0
alert = 80.0
format = " $percentage $icon"
format_alt = " $used/$total $icon"
if_command = "! [ \"$(df -P /home | awk 'NR==2 {print $1}')\" = \"$(df -P / | awk 'NR==2 {print $1}')\" ]"
merge_with_next = true

[[block]]
block = "disk_space"
path = "/home"
info_type = "used"
interval = 30
warning = 70.0
alert = 80.0
format = " $percentage $icon  "
format_alt = " $used/$total $icon  "
if_command = "! [ \"$(df -P /home | awk 'NR==2 {print $1}')\" = \"$(df -P / | awk 'NR==2 {print $1}')\" ]"
[block.icons_overrides]
disk_drive = "\ue1b0"
# # # # #

# performance
[[block]]
block = "cpu"
interval = 5
format = " $utilization $icon "
merge_with_next = true

[[block]]
block = "memory"
format = " $mem_used_percents $icon "
format_alt = " $mem_used/$mem_total $icon"
interval = 5
merge_with_next = true

[[block]]
block = "temperature"
interval = 5
format = " $average $icon "
chip = "*-isa-*"
# # # # #

[[block]]
block = "battery"
driver = "upower"
interval = 30
format = " $percentage $icon "
if_command = "test -e /sys/class/power_supply/BAT0"

[[block]]
block = "bluetooth"
mac = "D2:01:D1:C0:7C:55"
disconnected_format = ""
format = "{ $percentage|} $icon "

# audio
[[block]]
block = "bluetooth"
mac = "1A:2B:5B:FF:00:A3"
disconnected_format = ""
format = "{ $percentage|} $icon "
merge_with_next = true

[[block]]
block = "sound"
step_width = 2
driver = "pulseaudio"
format = "{ $volume|} $icon "
# # # # #

[[block]]
block = "time"
interval = 60
format = " $timestamp.datetime(f:'%a %d.%m %H:%M') $icon "

[[block]]
block = "notify"
driver = "dunst"
format = " $icon {$notification_count.eng(w:1) |}"
[[block.click]]
button = "left"
action = "show"
[[block.click]]
button = "right"
action = "toggle_paused"

[[block]]
block = "kdeconnect"
format = " $icon {$bat_charge $bat_icon |}{$notif_icon |}"
bat_good = 101

[[block]]
block = "custom"
command = "~/.config/i3/scripts/keyboard-layout"
interval = 1
